mod 'r_gito',
  :git => 'https://h0tbird@github.com/h0tbird/puppet-r_gito.git'

mod 'gitolite',
  :git => 'https://h0tbird@github.com/h0tbird/puppet-gitolite.git'

mod 'cgit',
  :git => 'https://h0tbird@github.com/h0tbird/puppet-cgit.git'

mod 'apache',
  :git => 'https://github.com/puppetlabs/puppetlabs-apache.git'
