#!/bin/bash

#------------------------------------------------------------------------------
# Wait for the network:
#------------------------------------------------------------------------------

[ "$WAIT_IFACE" ] && {

  RETRIES=20

  echo "[Init] Waiting for ${WAIT_IFACE} network..."

  while [ $RETRIES -gt 0 ]; do
    ip -o a | grep -q $WAIT_IFACE && break
    sleep 1; RETRIES=$((RETRIES - 1))
  done

  [ $RETRIES -eq 0 ] && {
    echo "[Init] There is no ${WAIT_IFACE} network"
    exit 1
  }

  echo "[Init] Interface ${WAIT_IFACE} is present"
}

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

[ -f /etc/ssh/ssh_host_rsa_key ] || {
  ssh-keygen -q -f /etc/ssh/ssh_host_rsa_key -t rsa -N ''
}

[ -f /etc/ssh/ssh_host_ecdsa_key ] || {
  ssh-keygen -q -f /etc/ssh/ssh_host_ecdsa_key -t ecdsa -N ''
}

chown -R git:git /home/git

cd /home/git && [ -d ./repositories ] && su git -c "

  [ ! -f ./.ssh/known_hosts ] && [ \"\$TRUST_HOSTS\" ] && {
    ssh-keyscan -H \$TRUST_HOSTS > .ssh/known_hosts
  }

  [ -d ./repositories/gitolite-admin.git ] && {
    mv ./repositories/gitolite-admin.git ./repositories/gitolite-admin.git-tmp
  }

  gitolite setup -a dummy &> /dev/null

  [ -d ./repositories/gitolite-admin.git-tmp ] && {
    rm -rf ./repositories/gitolite-admin.git
    mv ./repositories/gitolite-admin.git-tmp ./repositories/gitolite-admin.git
  }

  [ -d .gitolite/local/hooks/repo-specific ] || {
    mkdir -p .gitolite/local/hooks/repo-specific
    chmod 700 .gitolite/local/hooks/repo-specific
  }

  cp /etc/gitolite/gitolite.rc .gitolite.rc
  cp /etc/gitolite/post-receive .gitolite/hooks/common/
  rm -f projects.list

  cd ~/repositories/gitolite-admin.git && \
  GL_LIBDIR=/usr/share/gitolite3/lib hooks/post-update refs/heads/master

" || {

  echo '[Init] You must provide a repositories volume'
  exit 1
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $*"
exec $*
