#!/bin/bash

#------------------------------------------------------------------------------
# Run as 'git' user:
#------------------------------------------------------------------------------

[ $EUID -ne $(id -u git) ] && exec su git -c \
"$0 '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9' '${10}' '${11}' '${12}'"

#------------------------------------------------------------------------------
# Parse the command-line arguments:
#------------------------------------------------------------------------------

while [[ $# > 1 ]]; do

  case $1 in

    --admin)
      ADMIN="$2"
      shift
      ;;

    --owner)
      OWNER="$2"
      shift
      ;;

    --description)
      DESCR="$2"
      shift
      ;;

    --category)
      CATEG="$2"
      shift
      ;;

    --repo)
      REPO="$2"
      shift
      ;;

    --mirror)
      MIRRO="$2"
      ;;

    *) ;;

  esac

  shift

done

#------------------------------------------------------------------------------
# Configuration template:
#------------------------------------------------------------------------------

CONF="repo puppet-config\n"
[ -z "$OWNER" ] || CONF="${CONF} config gitweb.owner = ${OWNER}\n"
[ -z "$DESCR" ] || CONF="${CONF} config gitweb.description = ${DESCR}\n"
[ -z "$CATEG" ] || CONF="${CONF} config gitweb.category = ${CATEG}\n"
[ -z "$ADMIN" ] || CONF="${CONF} RW+ = ${ADMIN}\n"

#------------------------------------------------------------------------------
# Clone gitolite-admin:
#------------------------------------------------------------------------------

[ -d ~/gitolite-admin ] || \
git clone ~/repositories/gitolite-admin.git ~/gitolite-admin
