#!/bin/bash

#------------------------------------------------------------------------------
# Run as 'git' user:
#------------------------------------------------------------------------------

[ $EUID -ne $(id -u git) ] && exec su git -c \
"$0 '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9' '${10}' '${11}' '${12}'"

#------------------------------------------------------------------------------
# Parse the command-line arguments:
#------------------------------------------------------------------------------

while [ $# -gt 1 ]; do

  case $1 in

    --admin)
      ADMIN="$2"
      shift
      ;;

    --owner)
      OWNER="$2"
      shift
      ;;

    --description)
      DESCR="$2"
      shift
      ;;

    --category)
      CATEG="$2"
      shift
      ;;

    --repo)
      REPO="$2"
      NAME=$(echo $REPO | rev | awk -F'[/.]' '{print $2}' | rev)
      shift
      ;;

    --mirror)
      MIRRO=$(echo $REPO | sed 's/https:\/\//git@/;s/.com\//.com:/')
      ;;

    *) ;;

  esac

  shift

done

#------------------------------------------------------------------------------
# Validations and initializations:
#------------------------------------------------------------------------------

[ -z "$REPO" ] && echo 'You must provide a git repository' && exit 1
[ -d ~/.gitolite-admin.d ] || { mkdir ~/.gitolite-admin.d || exit 2; }
[ -d ~/repositories/${NAME}.git ] && rm -rf ~/repositories/${NAME}.git
[ -d ~/repositories/gitolite-admin.git ] || exit 3
[ -f ~/.gitolite-admin.d/00_header.conf ] || \
echo -e '##[ auto-generated ]##\n' > ~/.gitolite-admin.d/00_header.conf

#------------------------------------------------------------------------------
# Clone gitolite-admin and the imported repo:
#------------------------------------------------------------------------------

[ ! -d ~/gitolite-admin ] && {
git clone git@localhost:gitolite-admin ~/gitolite-admin || exit 4; }
cd ~/repositories && git clone --bare $REPO || exit 5

#------------------------------------------------------------------------------
# Generate the configuration:
#------------------------------------------------------------------------------

CONF="repo ${NAME}\n"
[ -z "$OWNER" ] || CONF="${CONF} config gitweb.owner = ${OWNER}\n"
[ -z "$DESCR" ] || CONF="${CONF} config gitweb.description = ${DESCR}\n"
[ -z "$CATEG" ] || CONF="${CONF} config gitweb.category = ${CATEG}\n"
[ -z "$MIRRO" ] || CONF="${CONF} config gitolite.mirror.simple = ${MIRRO}\n"
[ -z "$ADMIN" ] || CONF="${CONF} RW+ = ${ADMIN}"

echo -e $CONF > ~/.gitolite-admin.d/${NAME}.conf || exit 6
awk '/auto-generated/{exit}1' ~/gitolite-admin/conf/gitolite.conf > /tmp/conf
cat ~/.gitolite-admin.d/*.conf >> /tmp/conf
cat /tmp/conf > ~/gitolite-admin/conf/gitolite.conf

#------------------------------------------------------------------------------
# Commit and push:
#------------------------------------------------------------------------------

cd ~/gitolite-admin
git commit -am "Auto imported '${NAME}' repo"
git push
